### PR TITLE
Database

### PR DESCRIPTION
**Pull request by ViktoriiaKlymenko**

### CODE REVIEW

**Review by mihail-saharilenko — CHANGES_REQUESTED** [review]
1. All table names should be plural and start with a capital letter,
2. Seems like you have exchange rates in your currency table, so it is more logical to name it ExchangeRates or CurrencyRates.  
3. If you have table with currency rates, it would be logical to have Currency field in tables with prices to specify in what currency price is specified.
4. Products table should have some general info about product, like name, description, etc.
5. Pastry? "Выпечка"? What this table is about? If it is to specify which products were bought in each particular order, it should be named OrderProducts, and relations with Products and Orders should be reversed - each record in OrderProducts should be related to particular order and particular product. This way it will provide many-to-many relation between tables Orders and Products. If you had another idea and another meaning for this table - pls describe what was your intention.

**Review by mihail-saharilenko — CHANGES_REQUESTED** [review]
Please take a look at the comments above.

**Review by mihail-saharilenko — CHANGES_REQUESTED** [review]
.

**Comment by ViktoriiaKlymenko** [comment]
> 1. All table names should be plural and start with a capital letter,
> 2. Seems like you have exchange rates in your currency table, so it is more logical to name it ExchangeRates or CurrencyRates.
> 3. If you have table with currency rates, it would be logical to have Currency field in tables with prices to specify in what currency price is specified.
> 4. Products table should have some general info about product, like name, description, etc.
> 5. Pastry? "Выпечка"? What this table is about? If it is to specify which products were bought in each particular order, it should be named OrderProducts, and relations with Products and Orders should be reversed - each record in OrderProducts should be related to particular order and particular product. This way it will provide many-to-many relation between tables Orders and Products. If you had another idea and another meaning for this table - pls describe what was your intention.

Pastry in my app is entity, that describes all products that can be added by users. It contains all properties like name, weight, type etc. Also i have Products. It's like available products. In this place data about new added products is kept and could be pull out for users to give them a choice. And another one table - Orders, it's table that contains information about all products that have been ordered by consumer

**Comment by ViktoriiaKlymenko** [comment]
> 1. All table names should be plural and start with a capital letter,
> 2. Seems like you have exchange rates in your currency table, so it is more logical to name it ExchangeRates or CurrencyRates.
> 3. If you have table with currency rates, it would be logical to have Currency field in tables with prices to specify in what currency price is specified.
> 4. Products table should have some general info about product, like name, description, etc.
> 5. Pastry? "Выпечка"? What this table is about? If it is to specify which products were bought in each particular order, it should be named OrderProducts, and relations with Products and Orders should be reversed - each record in OrderProducts should be related to particular order and particular product. This way it will provide many-to-many relation between tables Orders and Products. If you had another idea and another meaning for this table - pls describe what was your intention.

Why should I make such columns in Products like name, description, if i had such in the table Pastry?

**Comment by mihail-saharilenko** [comment]
1. По поводу первых 3х пунктов ревью вопросов нет? Устрани эти недочёты пожалуйста
2. Если таблица Pastry содержит то, чем торгует твой магазин, то у неё неверная связь с таблицей Orders, т.к. в рамках одного заказа юзер должен иметь возможность несколько позиций товаров, а не одну, т.е. связть между Pastry и Orders должна быть многие-ко-многим.
3. Таблица Products в твоей схеме не несёт никакой информации, кроме как обеспечивает связь многие-ко-многим таблицы Pastry с таблицей Users. И тут первое - непонятно зачем эта связь (может, пояснишь?), и второе - имя таблицы, обеспечивающей связь многие-ко-многим, должно состоять из имён связываемых таблиц, в твоём случае это UsersPastry например.

**Review by mihail-saharilenko — CHANGES_REQUESTED** [review]
Уже лучше. Но еще не совсем правильно. 
1. Смотри, у тебя пока ещё остаётся проблема, что в рамках одного заказа можно купить только один товар. Чтобы дать возможность иметь разные позиции товара в одном заказе, тебе надо не привязывать каждый ордер к одной конкретной записи из Pastry (это сейчас у тебя связть один-ко-многим), а реализовать связь многие ко многим таблиц Orders и Pastries (через промежуточную таблицу).
2. Связь Users - Orders. Давай подумаем, один пользователь может иметь много заказов, верно. Но разве один заказ может быть оформлен на нескольких покупателей? Ведь получатель обычно указывается один. Итак: один юзер может иметь несколько заказов (связь один-ко-многим со стороны юзера), а один ордер не может быть связан сразу с несколькими юзерами (со стороны ордера связи один-ко-многим нет). Значит, в итоге, между таблицами Users и Orders должна быть связь один-ко-многим. Логично? Поправь пожалуйста, у тебя сейчас там связь многие-ко-многим.

**Review by mihail-saharilenko — APPROVED** [review]

**Review by mihail-saharilenko — APPROVED** [review]

**Pull request merged**
